# Generated by Django 4.1.7 on 2023-03-16 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trp_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='trp_db/static/pic')),
            ],
        ),
        migrations.CreateModel(
            name='Spareparts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('id_num', models.CharField(max_length=100)),
                ('cost', models.FloatField(max_length=100)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trp_db.category')),
            ],
        ),
    ]
