# Generated by Django 4.1.7 on 2023-03-16 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trp_db', '0002_category_images_spareparts'),
    ]

    operations = [
        migrations.AddField(
            model_name='spareparts',
            name='image_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trp_db.images'),
        ),
    ]
